### ISSUE TITLE
runtime error：'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'values'

### ISSUE THREAD

**Issue by shiboliu** [cent664/SSRIW#2]
![截图 2024-03-22 11-32-37](https://github.com/cent664/SSRIW/assets/44824960/237ec9bf-524a-4a94-9d48-b6eef90236a3)
![截图 2024-03-22 11-33-13](https://github.com/cent664/SSRIW/assets/44824960/137435b5-6366-49ad-b06b-53e686e403ad)

why？？？

**Comment by cent664** [comment]
I used distributed training across multiple GPUs and TPUs to train the model. The iterator produces distributed datasets. I used .values to access them.

https://www.tensorflow.org/api_docs/python/tf/distribute/DistributedValues
