### ISSUE TITLE
为什么嵌入的水印是与图像相关的而不是随机生成的64位水印？

### ISSUE THREAD

**Issue by qq843626244** [cent664/SSRIW#3]
为什么嵌入的水印是图像缩小到8*8然后二值化，而不是选择随机生成

**Comment by cent664** [comment]
Randomly generated watermark also works from my testing. I used the binarized cover image instead initially to see if it performs better.

**Comment by qq843626244** [comment]
> Randomly generated watermark also works from my testing. I used the binarized cover image instead initially to see if it performs better.

感谢您的回复，祝您取得更多成果
