### ISSUE TITLE
*** Please install the `scikit-image` package (instead of `skimage`) ***

### ISSUE THREAD

**Issue by ChinaApeng** [cent664/SSRIW#4]
I got an error trying to install the "skimage" package and was told that I should install it with the package name "scikit-image" instead of skimage.

**Comment by ChinaApeng** [comment]
I followed the prompts to install scikit-image, which is probably the full package name for skimage

**Comment by cent664** [comment]
Thank you for pointing it out. Updated requirements.txt.
